version: '3.9'
services:
  pg-0:
    image: bitnami/postgresql-repmgr:16.3.0-debian-12-r10
    ports:
      - 1234:5432
    volumes:
      - pg_0_data:/bitnami/postgresql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=db
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
  pg-1:
    image: bitnami/postgresql-repmgr:16.3.0-debian-12-r10
    ports:
      - 5432
    volumes:
      - pg_1_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=db
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080
    environment:
      - DB_SERVER=pg-0
      - DB_USERNAME=postgres
      - DB_PASSWORD=adminpassword
      - DB_DATABASE=postgres
volumes:
  pg_0_data:
    driver: local
  pg_1_data:
    driver: local
