version: '3.9'
services:
  pg-0:
    build:
      context: .
    ports:
      - 1234:5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=adminpassword
      - POSTGRESQL_DATABASE=postgres
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
  pg-1:
    build:
      context: .
    ports:
      - 5432
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=adminpassword
      - POSTGRESQL_DATABASE=postgres
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080
    environment:
      - DB_SERVER=pg-0
      - DB_USERNAME=postgres
      - DB_PASSWORD=adminpassword
      - DB_DATABASE=postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
