version: '3.9'
services:
  pg-0:
    image: bitnami/postgresql-repmgr:16.3.0-debian-12-r10
    command: "postgres -c config_file=/database/postgresql.conf"
    ports:
      - 1234:5432
    volumes:
      - pg_0_data:/bitnami/postgresql
      - ./database:/database
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=db
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-0
      - REPMGR_NODE_NETWORK_NAME=pg-0
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
  pg-1:
    image: bitnami/postgresql-repmgr:16.3.0-debian-12-r10
    command: "postgres -c config_file=/database/postgresql.conf"
    ports:
      - 5432
    volumes:
      - pg_1_data:/bitnami/postgresql
      - ./database:/database
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=db
      - REPMGR_PASSWORD=repmgrpassword
      - REPMGR_PRIMARY_HOST=pg-0
      - REPMGR_PARTNER_NODES=pg-0,pg-1
      - REPMGR_NODE_NAME=pg-1
      - REPMGR_NODE_NETWORK_NAME=pg-1
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080
    environment:
      - DB_SERVER=pg-0
      - DB_USERNAME=postgres
      - DB_PASSWORD=adminpassword
      - DB_DATABASE=postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
volumes:
  pg_0_data: {}
  pg_1_data: {}
